insert into User (id, username, password, email, fullname) values (0, 'admin', 'admin', 'admin@gmail.com', 'Admin Admin');
call next value for hibernate_sequence;
insert into User (id, username, password, email, fullname) values (1, 'a.mitev', '123456', 'adrian.mitev@gmail.com', 'Adrian Mitev');
call next value for hibernate_sequence;
insert into User (id, username, password, email, fullname) values (2, 'i.boev', '123456', 'boev.ilian@gmail.com', 'Ilian Boev');
call next value for hibernate_sequence;
insert into User (id, username, password, email, fullname) values (3, 'b.blajev', '123456', 'bobi.blajev@gmail.com', 'Bobi Blajev');
call next value for hibernate_sequence;
insert into User (id, username, password, email, fullname) values (4, 'y.myuysa', '123456', 'yukseldm@gmail.com', 'Yuksel Myuysa');
call next value for hibernate_sequence;
insert into User (id, username, password, email, fullname) values (5, 'p.ivanov', '123456', 'pldivanov91@abv.bg', 'Plamen Ivanov');
call next value for hibernate_sequence;
insert into User (id, username, password, email, fullname) values (6, 's.djulgerova', '123456', 'sdjulgerova@gmail.com', 'Stella Djulgerova');
call next value for hibernate_sequence;
insert into User (id, username, password, email, fullname) values (7, 'g.shefkedov', '123456', 'g.shefkedov@gmail.com', 'Gunesh Shefkedov');
call next value for hibernate_sequence;
insert into User (id, username, password, email, fullname) values (8, 'm.vladinova', '123456', 'm.vladinova@gmail.com', 'Monika Vladinova');
call next value for hibernate_sequence;
insert into User (id, username, password, email, fullname) values (9, 'y.nikolova', '123456', 'y.nikolova@gmail.com', 'Qnica Nikolova');
call next value for hibernate_sequence;
insert into User (id, username, password, email, fullname) values (10, 'r.ivanov', '123456', 'r.ivanov@gmail.com', 'Radostin Ivanov');
call next value for hibernate_sequence;
insert into Article (id, title, content, author, dateOfCreation, lastModificationDate) values(1, 'history', 'babababbababa', 'Gosho Goshev',  '2015-10-08',  '2015-10-09')